// Generated by CoffeeScript 1.9.3
var APISchema, RenderableSchema,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

RenderableSchema = require('./RenderableSchema');

APISchema = (function(superClass) {
  extend(APISchema, superClass);

  function APISchema() {
    this.__template = "/*\n * <%=name%>.js\n * Schema Generated by API-Hero\n * Add custom Schema Validators, Types and Methods below\n */\nmodule.exports = function(<%=name%>) {\n\n};";
    APISchema.__super__.constructor.apply(this, arguments);
  }

  return APISchema;

})(RenderableSchema);

module.exports = APISchema;
