// Generated by CoffeeScript 1.7.1
var ClientSchema, RikkiTikkiAPI, SchemaRenderer, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

RikkiTikkiAPI = module.parent.exports;

module.exports = {};

module.exports.RikkiTikkiAPI = RikkiTikkiAPI;

SchemaRenderer = require('./SchemaRenderer');

ClientSchema = (function(_super) {
  __extends(ClientSchema, _super);

  function ClientSchema() {
    return ClientSchema.__super__.constructor.apply(this, arguments);
  }

  return ClientSchema;

})(SchemaRenderer);

ClientSchema.prototype.__template = "(function() {\n  var __hasProp = {}.hasOwnProperty,\n    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },\n    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },\n    __slice = [].slice;\n  <%=ns%><%=name%> = (function(_super) {\n      __extends(<%=name%>, _super);\n      function <%=name%>() {\n        <% _.each( schema, function(value,key) {%>\n          this.<%=key%> = <%=JSON.stringify(value, null, 2)%>;\n        <%});%>\n      }\n  })(RikkiTikki.Schema);\n);";

module.exports = ClientSchema;

module.exports.RikkiTikki = RikkiTikkiAPI;
