// Generated by CoffeeScript 1.10.0
var Hash, SchemaOptions, _,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Hash = require('strictly-hash');

SchemaOptions = (function(superClass) {
  extend(SchemaOptions, superClass);

  function SchemaOptions() {
    var o;
    console.log(_.concat);
    SchemaOptions.__super__.constructor.call(this, o = {
      idInjection: true,
      plural: null,
      validateUpsert: null
    }, _.concat(_.keys(o), SchemaOptions.mixin_keys));
  }

  return SchemaOptions;

})(Hash);

SchemaOptions.mixin_keys = ['mongodb', 'mysql'];

module.exports = SchemaOptions;
