// Generated by CoffeeScript 1.9.3
var APIOptions, AbstractMonitor, SchemaManager, SchemaMonitor, Util, _, fs, path,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

fs = require('fs');

path = require('path');

Util = require('../utils');

APIOptions = require('../config/APIOptions');

SchemaManager = require('../schema/SchemaManager');

AbstractMonitor = require('../base_class/AbstractMonitor');

SchemaMonitor = (function(superClass) {
  extend(SchemaMonitor, superClass);

  SchemaMonitor.prototype.__exclude = [/^(_+.*|\.+\.?)$/];

  function SchemaMonitor() {
    Util.File.ensureDirExists(this.__path = APIOptions.get('schema_path'));
    SchemaMonitor.__super__.constructor.call(this);
    if (!APIOptions.get('monitoring_enabled')) {
      return;
    }
    setTimeout(((function(_this) {
      return function() {
        var _initialized;
        if (!_initialized) {
          _initialized = true;
          return _this.emit('init', {
            '0': {
              'added': _this.getCollection()
            }
          });
        }
      };
    })(this)), 600);
  }

  SchemaMonitor.prototype.refresh = function(callback) {
    var ex;
    ex = [];
    return SchemaManager.getInstance().listSchemas((function(_this) {
      return function(e, names) {
        var list;
        list = _.compact(_.map(names, function(v) {
          var _path, stats;
          if (!fs.existsSync(_path = "" + _this.__path + path.sep + v + ".js")) {
            _this.__collection.removeItemAt(_this.getNames().indexOf(v));
            return null;
          }
          if ((_this.filter(v)) && ((stats = fs.statSync(_path)) != null)) {
            return {
              name: v,
              updated: new Date(stats.mtime).getTime()
            };
          }
        }));
        if (list.length > 0) {
          _.each(list, function(value) {
            var idx;
            if (0 <= (idx = _this.getNames().indexOf(value.name))) {
              ex.push(value);
              if (_this.__collection.getItemAt(idx).updated !== value.updated) {
                return _this.__collection.setItemAt(value, idx);
              }
            }
          });
          if ((list = _.difference(list, ex)).length) {
            _this.__collection.addAll(list);
          }
        }
        return typeof callback === "function" ? callback(e, list) : void 0;
      };
    })(this));
  };

  SchemaMonitor.prototype.startPolling = function() {
    return this.__iVal != null ? this.__iVal : this.__iVal = fs.watch(this.__path, (function(_this) {
      return function(event, filename) {
        var e;
        try {
          return SchemaManager.getInstance().load();
        } catch (_error) {
          e = _error;
          return console.log(e);
        } finally {
          _this.refresh();
        }
      };
    })(this));
  };

  SchemaMonitor.prototype.stopPolling = function() {
    if (this.__iVal) {
      this.__iVal.close();
      return this.__iVal = null;
    }
  };

  return SchemaMonitor;

})(AbstractMonitor);

module.exports = SchemaMonitor;
