/*
 * Configurations.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Configurations = new API.Schema(
  API.extend(API.getSchemaTree('Configurations'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Configurations.virtuals = {
  
};

/*
 * Static Methods
 */
Configurations.statics = {
  
};

/*
 * Custom Schema Validators
 */
Configurations.validators = {
  
};

module.exports = API.model('Configurations', Configurations);