/*
 * Created8.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created8 = new API.Schema(
  API.extend(API.getSchemaTree('Created8'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created8.virtuals = {
  
};

/*
 * Static Methods
 */
Created8.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created8.validators = {
  
};

module.exports = API.model('Created8', Created8);