/*
 * Created15.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created15 = new API.Schema(
  API.extend(API.getSchemaTree('Created15'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created15.virtuals = {
  
};

/*
 * Static Methods
 */
Created15.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created15.validators = {
  
};

module.exports = API.model('Created15', Created15);