/*
 * Created14.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created14 = new API.Schema(
  API.extend(API.getSchemaTree('Created14'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created14.virtuals = {
  
};

/*
 * Static Methods
 */
Created14.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created14.validators = {
  
};

module.exports = API.model('Created14', Created14);