/*
 * Created7.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created7 = new API.Schema(
  API.extend(API.getSchemaTree('Created7'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created7.virtuals = {
  
};

/*
 * Static Methods
 */
Created7.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created7.validators = {
  
};

module.exports = API.model('Created7', Created7);