/*
 * Created21.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created21 = new API.Schema(
  API.extend(API.getSchemaTree('Created21'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created21.virtuals = {
  
};

/*
 * Static Methods
 */
Created21.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created21.validators = {
  
};

module.exports = API.model('Created21', Created21);