/*
 * Created18.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created18 = new API.Schema(
  API.extend(API.getSchemaTree('Created18'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created18.virtuals = {
  
};

/*
 * Static Methods
 */
Created18.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created18.validators = {
  
};

module.exports = API.model('Created18', Created18);