/*
 * Created.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created = new API.Schema(
  API.extend(API.getSchemaTree('Created'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created.virtuals = {
  
};

/*
 * Static Methods
 */
Created.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created.validators = {
  
};
//console.log( API.model('Created', Created).toClientSchema() );
module.exports = API.model('Created', Created);