/*
 * Created12.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created12 = new API.Schema(
  API.extend(API.getSchemaTree('Created12'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created12.virtuals = {
  
};

/*
 * Static Methods
 */
Created12.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created12.validators = {
  
};

module.exports = API.model('Created12', Created12);