/*
 * Created4.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created4 = new API.Schema(
  API.extend(API.getSchemaTree('Created4'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created4.virtuals = {
  
};

/*
 * Static Methods
 */
Created4.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created4.validators = {
  
};

module.exports = API.model('Created4', Created4);