/*
 * Created17.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created17 = new API.Schema(
  API.extend(API.getSchemaTree('Created17'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created17.virtuals = {
  
};

/*
 * Static Methods
 */
Created17.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created17.validators = {
  
};

module.exports = API.model('Created17', Created17);