/*
 * Created20.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created20 = new API.Schema(
  API.extend(API.getSchemaTree('Created20'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created20.virtuals = {
  
};

/*
 * Static Methods
 */
Created20.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created20.validators = {
  
};

module.exports = API.model('Created20', Created20);