/*
 * Created13.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created13 = new API.Schema(
  API.extend(API.getSchemaTree('Created13'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created13.virtuals = {
  
};

/*
 * Static Methods
 */
Created13.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created13.validators = {
  
};

module.exports = API.model('Created13', Created13);