/*
 * Created19.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created19 = new API.Schema(
  API.extend(API.getSchemaTree('Created19'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created19.virtuals = {
  
};

/*
 * Static Methods
 */
Created19.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created19.validators = {
  
};

module.exports = API.model('Created19', Created19);