/*
 * Created16.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created16 = new API.Schema(
  API.extend(API.getSchemaTree('Created16'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created16.virtuals = {
  
};

/*
 * Static Methods
 */
Created16.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created16.validators = {
  
};

module.exports = API.model('Created16', Created16);