/*
 * Created6.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created6 = new API.Schema(
  API.extend(API.getSchemaTree('Created6'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created6.virtuals = {
  
};

/*
 * Static Methods
 */
Created6.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created6.validators = {
  
};

module.exports = API.model('Created6', Created6);