/*
 * Created11.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Created11 = new API.Schema(
  API.extend(API.getSchemaTree('Created11'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Created11.virtuals = {
  
};

/*
 * Static Methods
 */
Created11.statics = {
  
};

/*
 * Custom Schema Validators
 */
Created11.validators = {
  
};

module.exports = API.model('Created11', Created11);