/*
 * Flubber.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Flubber = new API.Schema(
  API.extend(API.getSchemaTree('Flubber'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Flubber.virtuals = {
  
};

/*
 * Static Methods
 */
Flubber.statics = {
  
};

/*
 * Custom Schema Validators
 */
Flubber.validators = {
  
};

module.exports = API.model('Flubber', Flubber);