/*
 * Fooberry.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('../../lib');

var Fooberry = new API.Schema(
  API.extend(API.getSchemaTree('Fooberry'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Fooberry.virtuals = {
  
};

/*
 * Static Methods
 */
Fooberry.statics = {
  
};

/*
 * Custom Schema Validators
 */
Fooberry.validators = {
  
};

module.exports = API.model('Fooberry', Fooberry);