/*
 * Written.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Written = new API.Schema(
  API.extend(API.getSchemaTree('Written'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Written.virtuals = {
  fullName:function(first,last) {
      if (arguments.length) {
        this.set({first_name:first, last_name:last});
        return this;
      }
      
      return ''+ this.get('first_name') +' '+ this.get('last_name');
  }
};

/*
 * Static Methods
 */
Written.statics = {
  
};

/*
 * Custom Schema Validators
 */
Written.validators = {
  
};

module.exports = Written;