// Generated by CoffeeScript 1.7.1
var AbstractAdapter, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

AbstractAdapter = (function(_super) {
  __extends(AbstractAdapter, _super);

  AbstractAdapter.prototype.required = [];

  AbstractAdapter.prototype.params = {};

  function AbstractAdapter(params) {
    this.params = params != null ? params : {};
    _.each(this.required, (function(_this) {
      return function(param) {
        if (!(_this.params.hasOwnProperty(param))) {
          throw Error("required param '" + param + "' was not defined in the adapter params object");
        }
      };
    })(this));
  }

  AbstractAdapter.prototype.requestHandler = function(req, res) {};

  AbstractAdapter.prototype.responseHandler = function(req, res) {};

  AbstractAdapter.prototype.addRoute = function(route, method, handler) {};

  return AbstractAdapter;

})(Object);

module.exports = AbstractAdapter;
