// Generated by CoffeeScript 1.7.1
var AbstractAdapter, HapiAdapter,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AbstractAdapter = require('./AbstractAdapter');

HapiAdapter = (function(_super) {
  __extends(HapiAdapter, _super);

  function HapiAdapter() {
    return HapiAdapter.__super__.constructor.apply(this, arguments);
  }

  HapiAdapter.prototype.required = ['app'];

  HapiAdapter.prototype.addRoute = function(route, method, handler) {
    return this.params.app.route({
      path: route,
      method: method,
      handler: handler
    });
  };

  HapiAdapter.prototype.router = function() {
    return this.params.server;
  };

  return HapiAdapter;

})(AbstractAdapter);

module.exports = HapiAdapter;
