// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, _;

_ = require('underscore')._;

RikkiTikkiAPI = module.parent.exports;

module.exports.AbstractAdapter = require('./AbstractAdapter');

module.exports.express = require('./ExpressAdapter');

module.exports.hapi = require('./HapiAdapter');

module.exports.routes = require('./RoutesAdapter');

RikkiTikkiAPI.addRoutingAdapter = function(name, adapter) {
  return module.exports[name] = adapter;
};

RikkiTikkiAPI.getRoutingAdapter = function(name) {
  return module.exports[name];
};

RikkiTikkiAPI.removeRoutingAdapter = function(name) {
  return delete module.exports[name];
};

RikkiTikkiAPI.listRoutingAdapters = function() {
  return _.keys(module.exports);
};
