// Generated by CoffeeScript 1.7.1
var AdapterManager, RikkiTikkiAPI;

module.exports.RikkiTikkiAPI = RikkiTikkiAPI = module.parent.exports;

module.exports = AdapterManager = require('./AdapterManager');

RikkiTikkiAPI.Adapters = AdapterManager.getInstance();

RikkiTikkiAPI.Adapters.registerAdapter('express', require('./ExpressAdapter'));

RikkiTikkiAPI.Adapters.registerAdapter('hapi', require('./HapiAdapter'));

RikkiTikkiAPI.Adapters.registerAdapter('routes', require('./RoutesAdapter'));
