RenderableSchema  = require './RenderableSchema'
class APISchema extends RenderableSchema
  constructor:->
    @__template = """
    /*
     * <%=name%>.js
     * Schema Generated by API-Hero
     * Add custom Schema Validators, Types and Methods below
     */
    module.exports = function(<%=name%>) {
    
    };
    """
    APISchema.__super__.constructor.apply @, arguments
module.exports = APISchema
