// Generated by CoffeeScript 1.9.3
var AbstractRoute, RouteDestroy,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AbstractRoute = require('../../base_class/AbstractRoute');

RouteDestroy = (function(superClass) {
  extend(RouteDestroy, superClass);

  function RouteDestroy() {
    return RouteDestroy.__super__.constructor.apply(this, arguments);
  }

  RouteDestroy.prototype.handler = function(callback) {
    return (function(_this) {
      return function(req, res) {
        return _this.handler.destroy(function(e, result) {
          return typeof callback === "function" ? callback(res, e != null ? e : result) : void 0;
        });
      };
    })(this);
  };

  return RouteDestroy;

})(AbstractRoute);

module.exports = RouteDestroy;
