// Generated by CoffeeScript 1.9.3
var AbstractRoute, RouteUpdate,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AbstractRoute = require('../../base_class/AbstractRoute');

RouteUpdate = (function(superClass) {
  extend(RouteUpdate, superClass);

  function RouteUpdate() {
    return RouteUpdate.__super__.constructor.apply(this, arguments);
  }

  RouteUpdate.prototype.handler = function(callback) {
    return (function(_this) {
      return function(req, res) {
        return _this.handler.update(function(e, result) {
          return typeof callback === "function" ? callback(res, e != null ? e : result) : void 0;
        });
      };
    })(this);
  };

  return RouteUpdate;

})(AbstractRoute);

module.exports = RouteUpdate;
