// Generated by CoffeeScript 1.9.0
var APIOptions, Hash, path, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Hash = require('strictly-hash');

path = require('path');

APIOptions = (function(_super) {
  __extends(APIOptions, _super);

  function APIOptions(params) {
    var Fleek, o;
    if (params == null) {
      params = {};
    }
    Fleek = require('../..');
    APIOptions.__super__.constructor.call(this, o = _.extend({
      api_basepath: Fleek.API_BASEPATH,
      api_version: Fleek.API_VERSION,
      api_namespace: Fleek.API_NAMESPACE,
      config_filename: Fleek.CONFIG_FILENAME,
      config_path: Fleek.CONFIG_PATH,
      schema_path: Fleek.SCHEMA_PATH,
      schema_api_require_path: Fleek.SCHEMA_API_REQUIRE_PATH,
      destructive: Fleek.DESTRUCTIVE,
      wrap_schema_exports: Fleek.WRAP_SCHEMA_EXPORTS || true,
      adapter: Fleek.ADAPTER,
      debug: Fleek.DEBUG,
      default_datasource: Fleek.DEFAULT_DATASOURCE
    }, params), _.keys(o));
  }

  return APIOptions;

})(Hash);

module.exports = APIOptions;
