// Generated by CoffeeScript 1.9.3
var APIOptions, Hash, ReturnValue, Singleton, _, config_path, fs, path,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Hash = require('strictly-hash');

fs = require('fs');

path = require('path');

Singleton = require('../base_class/Singleton');

config_path = "" + (process.cwd()) + path.sep + "server" + path.sep + "api-hero.json";

APIOptions = (function(superClass) {
  extend(APIOptions, superClass);

  function APIOptions() {
    var o, params;
    params = fs.existsSync(config_path) ? require(config_path) : {};
    APIOptions.__super__.constructor.call(this, o = _.extend({
      api_basepath: '/api',
      api_version: '',
      api_path: '',
      api_namespace: '',
      schema_path: "" + (process.cwd()) + path.sep + "schemas",
      schema_api_require_path: "" + (process.cwd()) + path.sep + ".api-hero",
      data_path: "" + (process.cwd()) + path.sep + ".api-hero",
      trees_path: "" + (process.cwd()) + path.sep + ".api-hero" + path.sep + "trees",
      destructive: false,
      wrap_schema_exports: true,
      debug: process.NODE_ENV === void 0 || process.NODE_ENV === 'development',
      default_datasource: 'mongo',
      server_dir: './server',
      monitoring_enabled: true
    }, params), _.keys(o));
    this.set('api_path', (this.get('api_basepath')) + "/" + (this.get('api_version')) + "/");
  }

  return APIOptions;

})(Hash);

ReturnValue = (function(superClass) {
  extend(ReturnValue, superClass);

  function ReturnValue() {
    this.__opts = new APIOptions;
  }

  ReturnValue.prototype.getOpts = function() {
    return this.__opts;
  };

  return ReturnValue;

})(Singleton);

module.exports = ReturnValue.getInstance().getOpts();
