// Generated by CoffeeScript 1.9.0
var AppConfig, Hash, path, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

path = require('path');

Hash = require('strictly-hash');

AppConfig = (function(_super) {
  __extends(AppConfig, _super);

  function AppConfig() {
    var o;
    AppConfig.__super__.constructor.call(this, o = {
      data_path: "" + (process.cwd()) + path.sep + ".rikki-tikki",
      trees_path: "" + (process.cwd()) + path.sep + ".rikki-tikki" + path.sep + "trees"
    }, _.keys(o));
    this.seal();
  }

  return AppConfig;

})(Hash);

module.exports = AppConfig;
