// Generated by CoffeeScript 1.9.0
var ApiHero, ClientOptions, Hash, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Hash = require('../base_class/Hash');

ClientOptions = (function(_super) {
  __extends(ClientOptions, _super);

  function ClientOptions(params) {
    var ApiHero, o;
    if (params == null) {
      params = {};
    }
    ApiHero = require('../..');
    ClientOptions.__super__.constructor.call(this, o = _.extend({
      host: ApiHero.getApp().get('host'),
      port: ApiHero.getApp().get('post'),
      api_version: (ApiHero.getApp().get('version')) || 1
    }, params), _.keys(o));
  }

  return ClientOptions;

})(Hash);

module.exports = ClientOptions;

ApiHero = require('../..');
