// Generated by CoffeeScript 1.7.1
var Connection, Connector, EventEmitter, RikkiTikkiAPI, Util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

Util = RikkiTikkiAPI.Util;

EventEmitter = require('events').EventEmitter;

Connector = null;

Connection = (function(_super) {
  __extends(Connection, _super);

  function Connection(args, opts) {
    this.opts = opts != null ? opts : {};
    Connector = require((new Util.Capabilities()).mongooseSupported() && !this.opts.forceNative ? './MongooseConnection' : './NativeConnection');
    this.__conn = new Connector(args, this.opts);
    this.__conn.on('open', (function(_this) {
      return function(conn) {
        return _this.emit('open', conn);
      };
    })(this));
    this.__conn.on('close', (function(_this) {
      return function(evt) {
        return _this.handleClose(evt);
      };
    })(this));
    this.__conn.on('error', (function(_this) {
      return function(e) {
        console.log("error: " + e);
        return _this.emit('error', "" + e);
      };
    })(this));
    if (args != null) {
      this.connect(args);
    }
    this;
  }

  Connection.prototype.handleClose = function(evt) {
    this.__conn = null;
    return this.emit('close');
  };

  Connection.prototype.connect = function(args) {
    return this.__conn.connect(args);
  };

  Connection.prototype.getConnection = function() {
    return this.__conn.getConnection();
  };

  Connection.prototype.getMongoDB = function() {
    return this.__conn.getMongoDB();
  };

  Connection.prototype.getDatabaseName = function() {
    return this.__conn.getDatabaseName();
  };

  Connection.prototype.isConnected = function() {
    return this.__conn.isConnected();
  };

  Connection.prototype.getCollectionNames = function(callback) {
    return this.__conn.getCollectionNames((function(_this) {
      return function(e, names) {
        return typeof callback === "function" ? callback(e, names) : void 0;
      };
    })(this));
  };

  Connection.prototype.close = function(callback) {
    return this.__conn.close((function(_this) {
      return function(e) {
        return typeof callback === "function" ? callback(e) : void 0;
      };
    })(this));
  };

  return Connection;

})(EventEmitter);

module.exports = Connection;

module.exports.RikkiTikkiAPI = RikkiTikkiAPI;
