{_}             = require 'underscore'
RikkiTikkiAPI   = module.parent.exports
module.exports = {}
module.exports.RikkiTikkiAPI = RikkiTikkiAPI
Util            = RikkiTikkiAPI.Util
SchemaRenderer  = require './SchemaRenderer'
class APISchema extends SchemaRenderer
APISchema::__template = """
/*
 * <%=name%> Schema
 * Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var RikkiTikkiAPI = require('rikki-tikki').API;
#{if Util.Capabilities.mongooseSupported() then "var mongoose = require('mongoose')" else ""};
var <%=name%> = new #{if Util.Capabilities.mongooseSupported() then 'mongoose.Schema' else 'RikkiTikkiAPI.Schema'}(
  _.extend(RikkiTikkiAPI.getSchemaTree('<%=name%>'),
  {
    // place custom Schema Type overrides here
  })
);
/*
 * Virtual Getters/Setters
 */
<%=name%>.virtuals = {
  
};

/*
 * Static Methods
 */
<%=name%>.statics = {
  
}

/*
 * Custom Schema Validators
 */
<%=name%>.validators = {
  
}

module.exports = <%=name%>;
"""
module.exports = APISchema