// Generated by CoffeeScript 1.7.1
var ClientSchema, RikkiTikkiAPI, Util, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

RikkiTikkiAPI = module.parent.exports;

Util = RikkiTikkiAPI.Util;

ClientSchema = (function(_super) {
  __extends(ClientSchema, _super);

  ClientSchema.prototype.toJSON = function() {
    return _.clone(this);
  };

  ClientSchema.prototype.toString = function(spacer) {
    return JSON.stringify(this, ClientSchema.replacer, spacer);
  };

  ClientSchema.prototype.toSource = function() {
    var ns, schema;
    ns = ((ns = RikkiTikkiAPI.API_NAMESPACE.concat('.')) !== '.' ? ns : '');
    schema = JSON.parse(this.toString());
    delete schema.name;
    return _.template(ClientSchema.template, {
      name: RikkiTikkiAPI.Util.capitalize(this.name),
      schema: schema,
      ns: ns
    });
  };

  function ClientSchema(name, obj, opts) {
    this.name = name;
    ClientSchema.__super__.constructor.call(this, obj, opts);
  }

  return ClientSchema;

})(RikkiTikkiAPI.Schema);

ClientSchema.replacer = function(key, value) {
  if ((value != null) && (0 >= _.keys(RikkiTikkiAPI.Schema.reserved).indexOf(key))) {
    return Util.Function.toString(value);
  } else {
    return void 0;
  }
};

ClientSchema.template = "(function() {\n  var __hasProp = {}.hasOwnProperty,\n    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },\n    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },\n    __slice = [].slice;\n  <%=ns%><%=name%> = (function(_super) {\n      __extends(<%=name%>, _super);\n      function <%=name%>() {\n        <% _.each( schema, function(value,key) {%>\n          this.<%=key%> = <%=JSON.stringify(value)%>;\n        <%});%>\n      }\n  })(RikkiTikki.Schema);\n);";

module.exports = ClientSchema;
