// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, SchemaManager, fs, path, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

fs = require('fs');

path = require('path');

RikkiTikkiAPI = module.parent.exports;

SchemaManager = (function(_super) {
  __extends(SchemaManager, _super);

  function SchemaManager() {
    this.__loader = new RikkiTikkiAPI.SchemaLoader;
  }

  SchemaManager.prototype.createSchema = function(name, _arg) {
    _arg.tree;
  };

  SchemaManager.prototype.alterSchema = function(name, _arg) {
    var s;
    _arg.tree;
    s = this.fetchSchema(name);
    return _.extend(s, tree);
  };

  SchemaManager.prototype.fetchSchema = function(name) {
    return this.__loader.getSchema(name);
  };

  SchemaManager.prototype.saveSchema = function() {
    return this.__loader.save();
  };

  return SchemaManager;

})(Object);
