// Generated by CoffeeScript 1.7.1
var SchemaLoader, fs, path, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

fs = require('fs');

path = require('path');

SchemaLoader = (function(_super) {
  __extends(SchemaLoader, _super);

  function SchemaLoader() {
    return SchemaLoader.__super__.constructor.apply(this, arguments);
  }

  SchemaLoader.prototype.createSchema = function(name, _arg) {
    _arg.tree;
  };

  SchemaLoader.prototype.alterSchema = function(name, _arg) {
    _arg.tree;
  };

  SchemaLoader.prototype.fetchSchema = function(name) {};

  SchemaLoader.prototype.renderSchema = function() {};

  SchemaLoader.prototype.saveSchema = function() {};

  return SchemaLoader;

})(Object);
