// Generated by CoffeeScript 1.9.0
var SyncOperation,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

SyncOperation = (function(_super) {
  __extends(SyncOperation, _super);

  function SyncOperation(_at_kind, _at_data, _at_operation) {
    this.kind = _at_kind;
    this.data = _at_data;
    this.operation = _at_operation;
    Object.freeze(this);
  }

  return SyncOperation;

})(Object);

module.exports = SyncOperation;
