// Generated by CoffeeScript 1.7.1
var SyncOperation,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SyncOperation = (function(_super) {
  __extends(SyncOperation, _super);

  function SyncOperation(name, operation) {
    this.name = name;
    this.operation = operation;
    Object.freeze(this);
  }

  return SyncOperation;

})(Object);

module.exports = SyncOperation;
