// Generated by CoffeeScript 1.9.3
var EventEmitter, SyncInstance, SyncOperation, _,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

EventEmitter = require('events').EventEmitter;

SyncInstance = (function(superClass) {
  extend(SyncInstance, superClass);

  function SyncInstance(kind, clazz) {
    var _t;
    this.kind = kind;
    if (!this.kind) {
      throw 'kind is required';
    }
    if ((_t = typeof this.kind) !== 'string') {
      throw "kind was required to be string type was " + _t;
    }
    if (!clazz) {
      throw 'clazz is required';
    }
    if (!((clazz.getInstance != null) && typeof clazz.getInstance === 'function')) {
      throw 'clazz must be instance of Singleton';
    }
    this.targetInstance = clazz.getInstance().on('init', (function(_this) {
      return function() {
        return _this.onInit.apply(_this, arguments);
      };
    })(this)).on('changed', (function(_this) {
      return function() {
        return _this.onChanged.apply(_this, arguments);
      };
    })(this));
  }

  SyncInstance.prototype.onInit = function(data) {};

  SyncInstance.prototype.onChanged = function(data) {
    var _ops, done, opTypes;
    _ops = [];
    opTypes = _.keys(data);
    done = _.after(opTypes.length, (function(_this) {
      return function() {
        return _this.emit('changed', _ops);
      };
    })(this));
    return _.each(opTypes, (function(_this) {
      return function(operation) {
        return _.each(data[operation], function(item) {
          _ops.push(new SyncOperation(_this.kind, item, operation));
          return done();
        });
      };
    })(this));
  };

  return SyncInstance;

})(EventEmitter);

module.exports = SyncInstance;

SyncOperation = require('./SyncOperation');
