// Generated by CoffeeScript 1.9.3
var SyncOperation,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SyncOperation = (function(superClass) {
  extend(SyncOperation, superClass);

  function SyncOperation(kind, data, operation) {
    this.kind = kind;
    this.data = data;
    this.operation = operation;
    Object.freeze(this);
  }

  return SyncOperation;

})(Object);

module.exports = SyncOperation;
