// Generated by CoffeeScript 1.9.0
var APIOptions, CollectionManager, DataSource, DataSourceWrapper, EventEmitter, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

EventEmitter = require('events').EventEmitter;

DataSource = require('loopback-datasource-juggler').DataSource;

APIOptions = require('../config/APIOptions');

CollectionManager = require('../collections/CollectionManager');

DataSourceWrapper = (function(_super) {
  __extends(DataSourceWrapper, _super);

  function DataSourceWrapper(NameOrDS, options) {
    DataSourceWrapper.__super__.constructor.call(this, NameOrDS, options);
    _.extend(this, EventEmitter);
    this.canBuildModelFromInstance = (function(_this) {
      return function() {
        return typeof _this.buildModelFromInstance === 'function';
      };
    })(this);
    this.isRelational = function() {
      return this.connector.relational || false;
    };
    this.isNoSQL = function() {
      return this.connector.nosql || ((this.name.match(/^(mongodb|Memory)+$/)) != null) || false;
    };
  }

  DataSourceWrapper.prototype.listModels = function() {
    var builtins, l;
    builtins = ['Model', 'PersistedModel', 'Email', 'Application', 'AnonymousModel_0', 'AnonymousModel_1', 'AnonymousModel_2', 'AnonymousModel_3', 'AnonymousModel_4', 'AnonymousModel_5', 'AccessToken', 'RoleMapping', 'Role', 'ACL', 'Scope', 'User', 'Change', 'Checkpoint'];
    l = _.filter(this.models, (function(_this) {
      return function(model, name) {
        var _ref;
        return (0 > builtins.indexOf(name)) && (model !== void 0) && (((_ref = model.getDataSource()) != null ? _ref.settings.name : void 0) === _this.sourceName);
      };
    })(this));
    return _.compact(_.map(l, function(m) {
      return m.definition.name;
    }));
  };

  DataSourceWrapper.prototype.listCollections = function(callback) {
    if (!((callback != null) && typeof callback === 'function')) {
      throw 'callback function required at argument[0]';
    }
    if (this.hasOwnProperty('ApiHero')) {
      return this.ApiHero.listCollections((function(_this) {
        return function(e, cols) {
          return callback(null, _.compact(_.map(cols, function(v) {
            var ex;
            if (!((ex = _this.ApiHero.exclude) && ex.length)) {
              return v;
            }
            if (!v.match(new RegExp("^(" + (ex.join('|')) + ")$"))) {
              return v;
            }
          })));
        };
      })(this));
    } else {
      return process.nextTick((function(_this) {
        return function() {
          return callback(null, _.keys(_this.models));
        };
      })(this));
    }
  };

  DataSourceWrapper.prototype.createCollection = function(name, json, opts) {
    return this.createModel.apply(this, arguments);
  };

  DataSourceWrapper.prototype.dropCollection = function(name, callback) {
    if (this.isRelational) {
      return this.dropTable(name, callback);
    }
    return this.collection(name, (function(_this) {
      return function(e, col) {
        return col.drop(callback);
      };
    })(this));
  };

  DataSourceWrapper.prototype.buildCollection = function(name, json, opts) {
    var callback, o;
    if (typeof opts === 'function') {
      callback = arguments[2];
      opts = {};
    }
    this.modelBuilder.on('initialize', (function(_this) {
      return function() {
        return console.log('initialized model');
      };
    })(this));
    if (!this.canBuildModelFromInstance()) {
      throw "cannot create collections on SQL connection";
    }
    if (typeof (o = this.buildModelFromInstance.apply(this, arguments)) !== 'function') {
      throw 'could not create model';
    }
    return o;
  };

  DataSourceWrapper.prototype.getCollection = function(name) {
    return console.log(this.models);
  };

  DataSourceWrapper.prototype.removeCollection = function(name) {};

  return DataSourceWrapper;

})(DataSource);

DataSourceWrapper.getDataSource = (function(_this) {
  return function(name) {
    var DataSourceManager;
    DataSourceManager = require('./DataSourceManager');
    return DataSourceManager.getInstance().getDataSource(name);
  };
})(this);

module.exports = DataSourceWrapper;
