// Generated by CoffeeScript 1.9.0
var Collection, CollectionManager, CollectionMonitor, DSManager, Singleton, Util, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Util = require('../utils');

Singleton = require('../base_class/Singleton');

CollectionManager = (function(_super) {
  __extends(CollectionManager, _super);

  CollectionManager.prototype.__cache = {};

  function CollectionManager() {
    this.__ds = DSManager.getInstance();
    this.refresh = (function(_this) {
      return function() {};
    })(this);
  }

  CollectionManager.prototype.createCollection = function(name, ds, json, opts, callback) {
    if (typeof opts === 'function') {
      if (callback == null) {
        callback = opts;
      }
      opts = {};
    }
    return Collection.create(name, ds, json, opts, (function(_this) {
      return function(e, collection) {
        if (e != null) {
          return typeof callback === "function" ? callback(e, null) : void 0;
        }
        _this.__cache[name] = collection instanceof Collection ? collection : new Collection(name);
        _this.refresh();
        return typeof callback === "function" ? callback(e, collection) : void 0;
      };
    })(this));
  };

  CollectionManager.prototype.dropCollection = function(name, callback) {
    return this.getCollection(name, (function(_this) {
      return function(e, collection) {
        if (e != null) {
          return typeof callback === "function" ? callback(e) : void 0;
        }
        if (collection == null) {
          return typeof callback === "function" ? callback('collection undefined') : void 0;
        }
        return collection.drop(function(e, res) {
          _this.refresh();
          return typeof callback === "function" ? callback(e, collection) : void 0;
        });
      };
    })(this));
  };

  CollectionManager.prototype.listCollections = function(callback) {
    return _.uniq(_.flatten(_.map(this.__ds.getDSNames(), (function(_this) {
      return function(name) {
        return _this.__ds.getDataSource(name).listCollections();
      };
    })(this))));
  };

  CollectionManager.prototype.renameCollection = function(oldName, newName, callback) {
    return this.getCollection(oldName, (function(_this) {
      return function(e, collection) {
        return collection.rename(newName, {
          dropTarget: true
        }, function(e, res) {
          _this.refresh();
          return typeof callback === "function" ? callback(e, res) : void 0;
        });
      };
    })(this));
  };

  CollectionManager.prototype.getCollection = function(name, callback) {
    var cm, collection, idx;
    if (((collection = this.__cache[name]) != null) && collection instanceof Collection) {
      return typeof callback === "function" ? callback(null, collection) : void 0;
    } else {
      cm = CollectionMonitor.getInstance();
      if (0 <= (idx = cm.__collection.getItemIndex(name))) {
        return typeof callback === "function" ? callback(null, (this.__cache[name] = new Collection(name)).getCollection()) : void 0;
      }
    }
    return typeof callback === "function" ? callback('collection not found', null) : void 0;
  };

  return CollectionManager;

})(Singleton);

module.exports = CollectionManager;

Collection = require('./Collection');

CollectionMonitor = require('./CollectionMonitor');

DSManager = require('../datasource/DataSourceManager');
