// Generated by CoffeeScript 1.9.0
var APIOptions, Collection, CollectionManager, CollectionMonitor, Singleton, Util, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Util = require('../utils');

Singleton = require('../base_class/Singleton');

APIOptions = require('../config/APIOptions');

Collection = require('./Collection');

CollectionMonitor = require('./CollectionMonitor');

CollectionManager = (function(_super) {
  __extends(CollectionManager, _super);

  function CollectionManager() {
    this.__monitor = CollectionMonitor.getInstance();
  }

  CollectionManager.prototype.createCollection = function(name, json, opts, callback) {
    return Collection.create.apply(this, arguments);
  };

  CollectionManager.prototype.dropCollection = function(name, callback) {
    if (typeof arguments[arguments.length - 1] !== 'function') {
      throw 'callback required';
    }
    return this.getCollection(name, (function(_this) {
      return function(e, col) {
        if (e != null) {
          return callback.apply(_this, arguments);
        }
        return col.drop(callback);
      };
    })(this));
  };

  CollectionManager.prototype.listCollections = function(dsNames, callback) {
    var list;
    if (typeof arguments[arguments.length - 1] !== 'function') {
      throw 'callback required';
    }
    if (typeof dsNames === 'function') {
      callback = arguments[0];
      dsNames = [APIOptions.get('default_datasource')];
    }
    if ((dsNames != null) && typeof dsNames === 'string') {
      dsNames = dsNames.split(',');
    }
    list = _.filter(CollectionMonitor.getInstance().getCollection(), (function(_this) {
      return function(v) {
        return 0 <= dsNames.indexOf(v.dsName);
      };
    })(this));
    return callback(null, list);
  };

  CollectionManager.prototype.renameCollection = function(name, newName, opts, callback) {
    return this.getCollection(name, (function(_this) {
      return function(e, col) {
        if (e != null) {
          return callback.apply(_this, arguments);
        }
        return col.rename(newName, opts, callback);
      };
    })(this));
  };

  CollectionManager.prototype.getCollection = function(name, callback) {
    var col;
    if (!((callback != null) && typeof callback === 'function')) {
      throw "callback required";
    }
    if (!((name != null) && typeof name === 'string')) {
      return callback("name required");
    }
    if ((col = _.where(this.__monitor.getCollection(), {
      name: name
    })).length) {
      return callback(null, col[0]);
    }
    return callback('collection not found');
  };

  return CollectionManager;

})(Singleton);

module.exports = CollectionManager;
