// Generated by CoffeeScript 1.7.1
var AdapterManager, ExpressAdapter, RikkiTikkiAPI, RoutesAdapter;

module.exports.RikkiTikkiAPI = RikkiTikkiAPI = module.parent.exports;

module.exports = AdapterManager = require('./AdapterManager');

RikkiTikkiAPI.Adapters = AdapterManager.getInstance();

RikkiTikkiAPI.Adapters.registerAdapter('express', ExpressAdapter = require('./ExpressAdapter'));

RikkiTikkiAPI.Adapters.registerAdapter('routes', RoutesAdapter = require('./RoutesAdapter'));
