// Generated by CoffeeScript 1.7.1
var AdapterManager, ClientLoader, CollectionManager, CollectionMonitor, EventEmitter, Model, RikkiTikkiAPI, SchemaManager, SchemaTree, SchemaTreeManager, SyncService, e, path, _, _collections, _connections, _router, _types,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

EventEmitter = require('events').EventEmitter;

path = require('path');

RikkiTikkiAPI = (function(_super) {
  __extends(RikkiTikkiAPI, _super);

  RikkiTikkiAPI.prototype.__adapter = null;

  RikkiTikkiAPI.prototype.__detected_adapter = null;

  function RikkiTikkiAPI(__options, callback) {
    var adapter, name, _i, _len, _ref;
    if (__options == null) {
      __options = new RikkiTikkiAPI.APIOptions;
    }
    if (!(RikkiTikkiAPI.Util.Object.isOfType(__options, RikkiTikkiAPI.APIOptions))) {
      __options = new RikkiTikkiAPI.APIOptions(__options);
    }
    _ref = ['express'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      if (RikkiTikkiAPI.Util.detectModule(name)) {
        if (this.__detected_adapter == null) {
          this.__detected_adapter = name;
        }
        break;
      }
    }
    RikkiTikkiAPI.getSchemas = (function(_this) {
      return function() {
        return RikkiTikkiAPI.SchemaManager.getInstance();
      };
    })(this);
    RikkiTikkiAPI.useAdapter = (function(_this) {
      return function(adapter, options) {
        var router;
        if (adapter) {
          if (typeof adapter === 'string') {
            if (0 <= RikkiTikkiAPI.Adapters.listAdapters().indexOf(adapter)) {
              _this.__adapter = new (RikkiTikkiAPI.Adapters.getAdapter(adapter))(options);
            } else {
              throw "Routing Adapter '" + adapter + "' was not registered. Use RikkiTikkiAPI.Adapters.registerAdapter(name, class)";
            }
          } else {
            _this.__adapter = adapter;
          }
          if (RikkiTikkiAPI.getConnection() != null) {
            if ((_this.__adapter != null) && ((router = new RikkiTikkiAPI.Router) != null)) {
              return router.intializeRoutes();
            }
          } else {
            return _this.once('open', function() {
              if ((_this.__adapter != null) && ((router = new RikkiTikkiAPI.Router) != null)) {
                return router.intializeRoutes();
              }
            });
          }
        } else {
          throw 'param \'adapter\' is required';
        }
      };
    })(this);
    RikkiTikkiAPI.getAdapter = (function(_this) {
      return function() {
        return _this.__adapter;
      };
    })(this);
    if ((adapter = __options.get('adapter')) != null) {
      RikkiTikkiAPI.useAdapter(adapter);
    }
    (this.__config = new RikkiTikkiAPI.ConfigLoader(__options)).load((function(_this) {
      return function(e, data) {
        if (e != null) {
          return typeof callback === "function" ? callback(e) : void 0;
        }
        return _this.connect(_this.__config.getEnvironment(RikkiTikkiAPI.Util.Env.getEnvironment()), {
          open: function() {
            if (__options.adapter != null) {
              RikkiTikkiAPI.useAdapter(__options.adapter);
            }
            if (RikkiTikkiAPI.Util.Env.isDevelopment()) {
              SyncService.getInstance();
            }
            return _this.emit('open', null, _this.__conn);
          },
          error: function(e) {
            return _this.emit('error', e, null);
          },
          close: function() {
            return _this.emit('close');
          }
        });
      };
    })(this));
    RikkiTikkiAPI.getOptions = (function(_this) {
      return function() {
        return __options;
      };
    })(this);
    if (typeof callback === "function") {
      callback(null, true);
    }
  }

  RikkiTikkiAPI.prototype.connect = function(dsn, opts) {
    this.__conn = new RikkiTikkiAPI.Connection;
    this.__conn.once('open', (function(_this) {
      return function(evt) {
        RikkiTikkiAPI.getConnection = function() {
          return _this.__conn;
        };
        return opts != null ? typeof opts.open === "function" ? opts.open(evt) : void 0 : void 0;
      };
    })(this));
    this.__conn.once('close', (function(_this) {
      return function(evt) {
        return opts != null ? typeof opts.close === "function" ? opts.close(evt) : void 0 : void 0;
      };
    })(this));
    this.__conn.once('error', (function(_this) {
      return function(e) {
        return opts != null ? typeof opts.error === "function" ? opts.error(e) : void 0 : void 0;
      };
    })(this));
    return this.__conn.connect(dsn);
  };

  RikkiTikkiAPI.prototype.disconnect = function(callback) {
    return this.__conn.close((function(_this) {
      return function(e, s) {
        delete SchemaManager.__instance;
        delete SchemaTreeManager.__instance;
        delete CollectionManager.__instance;
        delete SyncService.__instance;
        delete _this.__conn;
        return typeof callback === "function" ? callback(e, s) : void 0;
      };
    })(this));
  };

  return RikkiTikkiAPI;

})(EventEmitter);

module.exports = RikkiTikkiAPI;

RikkiTikkiAPI.DEBUG = false;

RikkiTikkiAPI.ADAPTER = null;

RikkiTikkiAPI.DESTRUCTIVE = false;

RikkiTikkiAPI.API_BASEPATH = '/api';

RikkiTikkiAPI.API_VERSION = '1';

RikkiTikkiAPI.API_NAMESPACE = '';

RikkiTikkiAPI.AUTH_CONFIG_PATH = "" + (process.cwd()) + path.sep + "configs" + path.sep + "auth";

RikkiTikkiAPI.CONFIG_PATH = "" + (process.cwd()) + path.sep + "configs";

RikkiTikkiAPI.CONFIG_FILENAME = 'db.json';

RikkiTikkiAPI.SCHEMA_PATH = "" + (process.cwd()) + path.sep + "schemas";

RikkiTikkiAPI.SCHEMA_TREES_FILE = 'schema.json';

RikkiTikkiAPI.WRAP_SCHEMA_EXPORTS = true;

RikkiTikkiAPI.getConnection = function() {
  return this.connection;
};

RikkiTikkiAPI.getAPIPath = function() {
  return "" + RikkiTikkiAPI.API_BASEPATH + "/" + RikkiTikkiAPI.API_VERSION;
};

RikkiTikkiAPI.createAdapter = function(type, options) {
  var param, _i, _len, _ref;
  _ref = ['type', 'options'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    param = _ref[_i];
    if (typeof param === 'undefined' || param === null) {
      throw "param '" + param + "' is not defined";
    }
  }
  return RikkiTikkiAPI.Adapters.createAdapter(type, options);
};

RikkiTikkiAPI.addRoute = (function(_this) {
  return function(path, operation, handler) {
    var _adapter;
    if ((_adapter = RikkiTikkiAPI.getAdapter()) != null) {
      return _adapter.addRoute(path, operation, handler);
    } else {
      throw new Error('Adapter is not defined');
    }
  };
})(this);

RikkiTikkiAPI.getSchemaManager = function() {
  return SchemaManager.getInstance();
};

RikkiTikkiAPI.getSchemaTreeManager = function() {
  return SchemaTreeManager.getInstance();
};

RikkiTikkiAPI.getCollectionManager = function() {
  return CollectionManager.getInstance();
};

RikkiTikkiAPI.getCollectionMonitor = function() {
  return CollectionMonitor.getInstance();
};

RikkiTikkiAPI.getSchemaTree = function(name) {
  var tree;
  if ((tree = SchemaTreeManager.getInstance().__trees[name])) {
    return tree;
  } else {
    return {};
  }
};

RikkiTikkiAPI.getOptions = function() {
  return new RikkiTikkiAPI.APIOptions;
};

RikkiTikkiAPI.listCollections = function() {
  return this.getCollectionMonitor().getNames();
};

RikkiTikkiAPI.extend = _.extend;

RikkiTikkiAPI.model = function(name, schema) {
  var model, type;
  if (schema == null) {
    schema = {};
  }
  if (!name) {
    throw "name is required for model";
  }
  if ((type = typeof name) !== 'string') {
    throw "name expected to be String type was '" + type + "'";
  }
  model = function model(data, opts) { if (!(this instanceof RikkiTikkiAPI.model)) return _.extend(arguments.callee, new RikkiTikkiAPI.Document( data, opts )); };
  model.modelName = name;
  model.schema = schema;
  model.toClientSchema = function() {
    return new RikkiTikkiAPI.ClientSchema(this.modelName, this.schema);
  };
  model.toAPISchema = function() {
    return new RikkiTikkiAPI.APISchema(this.modelName, this.schema);
  };
  return model;
};

try {
  require('rikki-tikki-client');
} catch (_error) {
  e = _error;
  throw new Error("rikki-tikki-client was not found. Try 'npm install rikki-tikki-client'");
}

RikkiTikkiAPI.Util = require('./classes/utils');

RikkiTikkiAPI.base_classes = require('./classes/base_class');

RikkiTikkiAPI.APIOptions = require('./classes/config/APIOptions');

_types = require('./classes/types');

RikkiTikkiAPI.OperationTypes = _types.OperationTypes;

RikkiTikkiAPI.DSN = require('mongo-dsn');

ClientLoader = require('./classes/client/ClientLoader');

_connections = require('./classes/connections');

RikkiTikkiAPI.Connection = _connections.Connection;

_router = require('./classes/router');

RikkiTikkiAPI.Router = _router.Router;

RikkiTikkiAPI.RoutingParams = _router.RoutingParams;

RikkiTikkiAPI.ConfigLoader = require('./classes/config/ConfigLoader');

RikkiTikkiAPI.Schema = require('./classes/schema/Schema');

RikkiTikkiAPI.APISchema = require('./classes/schema/APISchema');

RikkiTikkiAPI.ClientSchema = require('./classes/schema/ClientSchema');

AdapterManager = require('./classes/request_adapters/AdapterManager');

SchemaManager = require('./classes/schema/SchemaManager');

SchemaTree = require('./classes/schema_tree/SchemaTree');

SchemaTreeManager = require('./classes/schema_tree/SchemaTreeManager');

SyncService = require('./classes/services/SyncService');

_collections = require('./classes/collections');

CollectionManager = _collections.CollectionManager;

CollectionMonitor = _collections.CollectionMonitor;

RikkiTikkiAPI.Collection = _collections.Collection;

RikkiTikkiAPI.Document = _collections.Document;

Model = _collections.Model;
