// Generated by CoffeeScript 1.9.0
var Env;

Env = {};

Env.getEnvironment = function() {
  return process.env.NODE_ENV || 'development';
};

Env.isDevelopment = function() {
  return (this.getEnvironment().match(/^dev+(el|elopment)?$/)) != null;
};

Env.isProduction = function() {
  return (this.getEnvironment().match(/^prod+(uction)?$/)) != null;
};

module.exports = Env;
