// Generated by CoffeeScript 1.7.1
var FS, fs, path;

fs = require('fs');

path = require('path');

FS = {};

FS.name = function(_path) {
  return (path.basename(_path)).split('.').shift();
};

FS.writeFile = function(_path, data, options, callback) {
  if (typeof options === 'function') {
    callback = arguments[2];
    options = {
      encoding: 'utf8',
      flag: 'w'
    };
  }
  return fs.writeFile(_path, data, options, (function(_this) {
    return function(e) {
      if (e) {
        console.error("Failed to write file '" + _path + "'\nError: " + e);
      }
      return typeof callback === "function" ? callback(e) : void 0;
    };
  })(this));
};

FS.readFile = function(_path, options, callback) {
  if (typeof options === 'function') {
    callback = arguments[1];
    options = {
      encoding: 'utf8',
      flag: 'r'
    };
  }
  return fs.readFile("" + _path, options, (function(_this) {
    return function(e, data) {
      if (e != null) {
        console.error("Failed to read file '" + _path + "'\nError: " + e);
      }
      return typeof callback === "function" ? callback(e, data) : void 0;
    };
  })(this));
};

module.exports = FS;
