// Generated by CoffeeScript 1.9.0
var Capabilities, Util, path, _;

_ = require('lodash')._;

path = require('path');

Util = {};

Util.Env = require('./Env');

Util.File = require('./File');

Util.Function = require('fun-utils');

Util.Module = require('./Modules');

Util.String = require('./String');

Util.Object = require('./Object');

Capabilities = require('./Capabilities');

Util.getCapabilities = (function(_this) {
  return function() {
    return new Capabilities;
  };
})(this);

module.exports = Util;
