// Generated by CoffeeScript 1.9.0
var path, _;

_ = require('lodash')._;

path = require('path');

module.exports.detectModule = function(name) {
  return _.map(_.pluck((require.main || {}).children, 'filename'), function(p) {
    return path.dirname(p).split(path.sep).pop();
  }).indexOf(name) > -1;
};

module.exports.getModulePath = function(name) {
  var idx, names, paths;
  names = _.map(paths = _.pluck(require.cache || {}, 'id'), function(p) {
    return path.dirname(p).split(path.sep).pop();
  });
  if (0 <= (idx = names.indexOf(name))) {
    return paths[idx];
  } else {
    return null;
  }
};
