// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, SchemaService, Util, fs, path, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

fs = require('fs');

path = require('path');

RikkiTikkiAPI = module.parent.exports;

Util = RikkiTikkiAPI.Util;

SchemaService = (function(_super) {
  __extends(SchemaService, _super);

  function SchemaService() {
    RikkiTikkiAPI.getCollectionManitor().on('changed', (function(_this) {
      return function(data) {
        return _.each(_.keys(data), function(operation) {
          return _.each(data[operation], function(collection) {
            console.log(collection);
            return _this["collection" + (Util.String.capitalize(operation))](collection);
          });
        });
      };
    })(this));
  }

  SchemaService.prototype.collectionAdded = function(name) {
    return console.log("added collection: " + name);
  };

  SchemaService.prototype.collectionRemoved = function(name) {
    return console.log("removed collection: " + name);
  };

  SchemaService.prototype.schemaAdded = function(name) {
    return console.log("added schema: " + name);
  };

  SchemaService.prototype.schemaRemoved = function(name) {
    return console.log("removed schema: " + name);
  };

  return SchemaService;

})(RikkiTikkiAPI.base_classes.Singleton);

SchemaService.getInstance = function() {
  return this.__instance != null ? this.__instance : this.__instance = new SchemaService;
};

module.exports = SchemaService;
