// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, SchemaService, SchemaTreeManager, Util, fs, path, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

fs = require('fs');

path = require('path');

RikkiTikkiAPI = module.parent.exports;

Util = RikkiTikkiAPI.Util;

SchemaTreeManager = require('../schema_tree/SchemaTreeManager');

SchemaService = (function(_super) {
  __extends(SchemaService, _super);

  function SchemaService() {
    RikkiTikkiAPI.getCollectionManitor().on('changed', (function(_this) {
      return function(data) {
        return _.each(_.keys(data), function(operation) {
          return _.each(data[operation], function(collection) {
            return _this["collection" + (Util.String.capitalize(operation))](collection.name);
          });
        });
      };
    })(this));
  }

  SchemaService.prototype.collectionAdded = function(name) {
    return RikkiTikkiAPI.getCollectionManager().getCollection(name, (function(_this) {
      return function(e, col) {
        if (e != null) {
          return console.log(e);
        }
        return col.getTree(function(e, tree) {
          return SchemaTreeManager.getInstance().createTree(name, tree, function(e, done) {
            if (e != null) {
              return console.log("could not create SchemaTree file for '" + name + "'");
            }
          });
        });
      };
    })(this));
  };

  SchemaService.prototype.collectionRemoved = function(name) {
    return SchemaTreeManager.getInstance().destroyTree(name, (function(_this) {
      return function(e, done) {
        if (e != null) {
          return console.log("could not destroy SchemaTree file for '" + name + "'");
        }
      };
    })(this));
  };

  SchemaService.prototype.schemaAdded = function(name) {
    return console.log("added schema: " + name);
  };

  SchemaService.prototype.schemaRemoved = function(name) {
    return console.log("removed schema: " + name);
  };

  return SchemaService;

})(RikkiTikkiAPI.base_classes.Singleton);

SchemaService.getInstance = function() {
  return this.__instance != null ? this.__instance : this.__instance = new SchemaService;
};

module.exports = SchemaService;
