// Generated by CoffeeScript 1.7.1
var Env;

Env = {};

Env.getEnvironment = function() {
  return process.env.NODE_ENV || 'development';
};

Env.isDevelopment = function() {
  return Env.getEnvironment() === 'development';
};

module.exports = Env;
