// Generated by CoffeeScript 1.7.1
var File, fs, path;

fs = require('fs');

path = require('path');

File = {};

File.name = function(_path) {
  return (path.basename(_path)).split('.').shift();
};

File.writeFile = function(path, data, options, callback) {
  if (typeof options === 'function') {
    callback = arguments[1];
    options = {
      encoding: 'utf-8',
      flag: 'r'
    };
  }
  return fs.writeFile(path, "" + data, options, (function(_this) {
    return function(e) {
      if (e) {
        console.error("Failed to write file '" + path + "'\nError: " + e);
      }
      return typeof callback === "function" ? callback(e) : void 0;
    };
  })(this));
};

File.readFile = function(path, options, callback) {
  if (typeof options === 'function') {
    callback = arguments[1];
    options = {
      encoding: 'utf-8',
      flag: 'r'
    };
  }
  return fs.readFile(path, options, (function(_this) {
    return function(e, data) {
      if (e) {
        console.error("Failed to read file '" + path + "'\nError: " + e);
      }
      return typeof callback === "function" ? callback(e, data) : void 0;
    };
  })(this));
};

module.exports = File;
