// Generated by CoffeeScript 1.7.1
var Util, path, _;

_ = require('underscore')._;

path = require('path');

Util = {};

Util.detectModule = function(name) {
  return _.map(_.pluck(require.main.children, 'filename'), function(p) {
    return path.dirname(p).split(path.sep).pop();
  }).indexOf("" + name) > -1;
};

module.exports = Util;

Util.Capabilities = require('./Capabilities');

Util.Env = require('./Env');

Util.File = require('./File');

Util.Function = require('./Function');

Util.String = require('./String');

Util.Object = require('./Object');

Util.Query = require('./Query');
