// Generated by CoffeeScript 1.7.1
var Util, path, _;

_ = require('underscore')._;

path = require('path');

Util = {};

Util.capitalize = function(string) {
  return "" + (string.charAt(0).toUpperCase()) + (string.slice(1));
};

Util.queryToObject = function(string) {
  var o;
  o = {};
  decodeURIComponent(string).replace('?', '').split('&').forEach((function(_this) {
    return function(v, k) {
      var p;
      if ((p = v.split('=')).length === 2) {
        return o[p[0]] = p[1];
      }
    };
  })(this));
  return o;
};

Util.objectToQuery = function(object) {
  return (_.map(_.pairs(object || {}), (function(_this) {
    return function(v, k) {
      return v.join('=');
    };
  })(this))).join('&');
};

Util.getTypeOf = function(obj) {
  return Object.prototype.toString.call(obj).slice(8, -1);
};

Util.getFunctionName = function(fun) {
  var n;
  if ((n = fun.toString().match(/function+\s{1,}([a-zA-Z_0-9]*)/)) != null) {
    return n[1];
  } else {
    return null;
  }
};

Util.getConstructorName = function(fun) {
  var name;
  return fun.constructor.name || ((name = Util.getFunctionName(fun.constructor)) != null ? name : null);
};

Util.isOfType = function(value, kind) {
  return (this.getTypeOf(value)) === (this.getFunctionName(kind)) || value instanceof kind;
};

Util.detectModule = function(name) {
  return _.map(_.pluck(require.main.children, 'filename'), function(p) {
    return path.dirname(p).split(path.sep).pop();
  }).indexOf("" + name) > -1;
};

module.exports = Util;

Util.Capabilities = require('./Capabilities');

Util.Function = require('./Function');
