// Generated by CoffeeScript 1.7.1
var Query, _;

_ = require('underscore')._;

Query = {};

Query.objectToQuery = function(object) {
  return (_.map(_.pairs(object || {}), (function(_this) {
    return function(v, k) {
      return v.join('=');
    };
  })(this))).join('&');
};

Query.queryToObject = function(string) {
  var o;
  o = {};
  decodeURIComponent(string).replace('?', '').split('&').forEach((function(_this) {
    return function(v, k) {
      var p;
      if ((p = v.split('=')).length === 2) {
        return o[p[0]] = p[1];
      }
    };
  })(this));
  return o;
};

module.exports = Query;
