// Generated by CoffeeScript 1.7.1
var Str;

Str = {};

Str.capitalize = function(string) {
  return "" + (string.charAt(0).toUpperCase()) + (string.slice(1));
};

Str.stripNull = function(string) {
  return string.replace(/\0/g, '');
};

module.exports = Str;
