// Generated by CoffeeScript 1.9.0
var ArrayCollection, ModuleManager, RikkiTikkiAPI,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

ArrayCollection = require('js-arraycollection');

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

ModuleManager = (function(_super) {
  __extends(ModuleManager, _super);

  function ModuleManager() {
    var modules;
    ModuleManager.__super__.constructor.call(this);
    modules = new ArrayCollection([]).on('open', (function(_this) {
      return function() {
        return console.log('open');
      };
    })(this));
  }

  return ModuleManager;

})(RikkiTikkiAPI.base_classes.Singleton);
