// Generated by CoffeeScript 1.7.1
module.exports.RikkiTikkiAPI = module.parent.exports;

module.exports.routes = require('./routes');

module.exports.Router = require('./Router');

module.exports.RoutingParams = require('./RoutingParams');
