// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, Router, Routes, RoutingParams, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

Routes = require('./routes');

RoutingParams = require('./RoutingParams');

Router = (function(_super) {
  __extends(Router, _super);

  function Router(__db, __adapter) {
    this.__db = __db;
    this.__adapter = __adapter;
    if (!this.__adapter) {
      throw 'adapter must be defined';
    }
    this.__api_path = RikkiTikkiAPI.getAPIPath();
    this.__routes = new Routes(this.__db, this.__adapter);
    this.__db.on('open', (function(_this) {
      return function() {
        return _this.intializeRoutes();
      };
    })(this));
  }

  Router.prototype.getAdapter = function() {
    return this.__adapter;
  };

  Router.prototype.intializeRoutes = function() {
    var collections, operation, _i, _len, _ref, _results;
    this.__adapter.addRoute("" + this.__api_path + "/__schema__", 'get', (function(_this) {
      return function(req, res) {
        return _this.__adapter.responseHandler(res, {
          status: 200,
          content: RikkiTikkiAPI.schemas
        });
      };
    })(this));
    RikkiTikkiAPI.DEBUG && logger.log('debug', "" + name + ":");
    _ref = ['index', 'show', 'create', 'update', 'destroy'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      operation = _ref[_i];
      collections = RikkiTikkiAPI.getEnvironment() === 'development' ? [':collection'] : ['Test'];
      _results.push(_.each(collections, (function(_this) {
        return function(collection) {
          var path, route;
          switch (operation) {
            case 'show':
              path = "" + _this.__api_path + "/" + collection + "/:id";
              break;
            case 'update':
              path = "" + _this.__api_path + "/" + collection + "/:id";
              break;
            case 'create':
              path = "" + _this.__api_path + "/" + collection;
              break;
            case 'destroy':
              path = "" + _this.__api_path + "/" + collection + "/:id";
              break;
            case 'index':
              path = "" + _this.__api_path + "/" + collection;
              break;
            default:
              throw new Error("unrecognized REST operation type: '" + operation + "'");
          }
          _this.addRoute(route = new RoutingParams(path, operation));
          return RikkiTikkiAPI.DEBUG && logger.log('debug', "" + (route.method.toUpperCase()) + " " + route.path + " -> " + route.operation);
        };
      })(this)));
    }
    return _results;
  };

  Router.prototype.addRoute = function(params) {
    var handler;
    if (params == null) {
      params = {};
    }
    if (!RikkiTikkiAPI.Util.isOfType(params, RoutingParams)) {
      params = new RoutingParams(params.path, params.operation);
    }
    if ((handler = this.__routes.createRoute(params.method, params.path, params.operation)) != null) {
      return this.__adapter.addRoute(params.path, params.method, handler);
    }
  };

  return Router;

})(Object);

module.exports = Router;
