// Generated by CoffeeScript 1.7.1
var Collection,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Collection = (function(_super) {
  __extends(Collection, _super);

  function Collection(__collection) {
    this.__collection = __collection;
  }

  Collection.prototype.drop = function() {
    return this.__collection.drop();
  };

  Collection.prototype.dropIndex = function(name) {
    if (name === '_id') {
      throw "can not drop index on _id field";
    }
    return this.__collection.dropIndex(name);
  };

  Collection.prototype.dropIndexes = function() {
    return this.__collection.dropIndexes();
  };

  Collection.prototype.find = function(params) {};

  Collection.prototype.insert = function(data) {};

  Collection.prototype.update = function(data) {};

  Collection.prototype.upsert = function(data) {};

  Collection.prototype.show = function() {};

  Collection.prototype.destroy = function(data) {};

  return Collection;

})(Object);
