// Generated by CoffeeScript 1.7.1
var Collection, CollectionManager, Connection, EventEmitter, RikkiTikkiAPI, Util, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

Util = RikkiTikkiAPI.Util;

Connection = RikkiTikkiAPI.Connection;

Collection = module.parent.exports.Collection;

_ = require('underscore')._;

EventEmitter = require('events').EventEmitter;

CollectionManager = (function(_super) {
  __extends(CollectionManager, _super);

  CollectionManager.prototype.__cache = {};

  function CollectionManager(__conn) {
    this.__conn = __conn;
    if (!this.__conn) {
      throw Error('CollectionManager requires a Connection as arg1');
    }
    if (!Util.isOfType(this.__conn, Connection)) {
      throw Error("CollectionManager arg1 must be Connection. Type was '" + (typeof this.__conn) + "'");
    }
    this.__db = this.__conn.getMongoDB() || (function() {
      throw Error('Connection is broken');
    })();
  }

  CollectionManager.prototype.createCollection = function(name, opts, callback) {
    if (typeof opts === 'function') {
      if (callback == null) {
        callback = opts;
      }
      opts = {};
    }
    return this.__db.createCollection(name, opts, (function(_this) {
      return function(e, collection) {
        RikkiTikkiAPI.collectionMon.refresh();
        return typeof callback === "function" ? callback(e, collection) : void 0;
      };
    })(this));
  };

  CollectionManager.prototype.dropCollection = function(name, callback) {
    return this.getCollection(name, (function(_this) {
      return function(e, collection) {
        return collection.drop(function(e, res) {
          RikkiTikkiAPI.collectionMon.refresh();
          return typeof callback === "function" ? callback(e, collection) : void 0;
        });
      };
    })(this));
  };

  CollectionManager.prototype.renameCollection = function(oldName, newName, callback) {
    return this.getCollection(oldName, (function(_this) {
      return function(e, collection) {
        return collection.rename(newName, {
          dropTarget: true
        }, function(e, res) {
          RikkiTikkiAPI.collectionMon.refresh();
          return typeof callback === "function" ? callback(e, res) : void 0;
        });
      };
    })(this));
  };

  CollectionManager.prototype.getCollection = function(name, callback) {
    var collection;
    if (((collection = this.__cache[name]) != null) && collection instanceof Collection) {
      return typeof callback === "function" ? callback(null, _.clone(collection)) : void 0;
    } else {
      return this.__db.collection(name, (function(_this) {
        return function(e, collection) {
          if (collection) {
            collection = _.clone(_this.__cache[name] = new Collection(collection));
          }
          return typeof callback === "function" ? callback(e, collection) : void 0;
        };
      })(this));
    }
  };

  return CollectionManager;

})(EventEmitter);

CollectionManager.getInstance = function() {
  var conn;
  if (!(conn = RikkiTikkiAPI.getConnection())) {
    throw 'database is not connected';
  }
  return this.__instance != null ? this.__instance : this.__instance = new CollectionManager(conn);
};

module.exports = CollectionManager;
