// Generated by CoffeeScript 1.7.1
module.exports.RikkiTikkiAPI = module.parent.exports;

module.exports.CollectionManager = require('./CollectionManager');

module.exports.CollectionMonitor = require('./CollectionMonitor');
