// Generated by CoffeeScript 1.7.1
var RouteCreate, RouteDestroy, RouteIndex, RouteShow, RouteUpdate, Routes,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RouteIndex = require('./RouteIndex');

RouteShow = require('./RouteShow');

RouteCreate = require('./RouteCreate');

RouteUpdate = require('./RouteUpdate');

RouteDestroy = require('./RouteDestroy');

Routes = (function(_super) {
  __extends(Routes, _super);

  function Routes(__db, __adapter) {
    this.__db = __db;
    this.__adapter = __adapter;
  }

  Routes.prototype.createRoute = function(method, path, operation) {
    return this.__adapter.addRoute(path, method, typeof Routes[operation] === "function" ? Routes[operation](this.__db, this.__adapter.responseHandler) : void 0);
  };

  return Routes;

})(Object);

Routes.show = function(__db, callback) {
  this.__db = __db;
  return new RouteShow(this.__db, callback);
};

Routes.update = function(__db, callback) {
  this.__db = __db;
  return new RouteUpdate(this.__db, callback);
};

Routes.create = function(__db, callback) {
  this.__db = __db;
  return new RouteCreate(this.__db, callback);
};

Routes.destroy = function(__db, callback) {
  this.__db = __db;
  return new RouteDestroy(this.__db, callback);
};

Routes.index = function(__db, callback) {
  this.__db = __db;
  return new RouteIndex(this.__db, callback);
};

module.exports = Routes;

module.exports.RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;
