// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, RouteCreate,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

RouteCreate = (function(_super) {
  __extends(RouteCreate, _super);

  function RouteCreate(callback) {
    RouteCreate.__super__.constructor.call(this);
    return (function(_this) {
      return function(req, res) {
        return req.on('data', function(data) {
          var d;
          d = JSON.parse(data);
          return _this.__db.getMongoDB().collection(req.params.collection, function(e, collection) {
            return collection.insert(d, function(e, result) {
              if ((e != null) && (result[0]._id != null)) {
                return typeof callback === "function" ? callback(res, {
                  status: 500,
                  content: 'failed to create record'
                }) : void 0;
              }
              return typeof callback === "function" ? callback(res, {
                status: 200,
                content: {
                  _id: result[0]._id
                }
              }) : void 0;
            });
          });
        });
      };
    })(this);
  }

  return RouteCreate;

})(RikkiTikkiAPI.base_classes.BaseRoute);

module.exports = RouteCreate;
