// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, RouteIndex, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore')._;

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

RouteIndex = (function(_super) {
  __extends(RouteIndex, _super);

  function RouteIndex(callback) {
    var sanitize;
    RouteIndex.__super__.constructor.call(this);
    sanitize = function(query) {
      var filter, filtered, restricted;
      filter = null;
      filtered = [];
      restricted = [];
      filter = _.partial(_.without, _.keys(query));
      _.each(RikkiTikkiAPI.OperationTypes.query, (function(_this) {
        return function(v) {
          return filtered = filter(v);
        };
      })(this));
      _.each(filtered, (function(_this) {
        return function(v, k) {
          if (v.match(/^\$/)) {
            delete query[v];
          }
          if (restricted.indexOf(v >= 0)) {
            return delete query[v];
          }
        };
      })(this));
      return query;
    };
    return (function(_this) {
      return function(req, res) {
        if (RikkiTikkiAPI.isDevelopment()) {
          _this.createCollection(req.params.collection);
        }
        return _this.__db.getMongoDB().collection(req.params.collection, function(e, collection) {
          return collection.find(sanitize(JSON.parse(req.query.where || "{}")), function(e, results) {
            if (e != null) {
              return typeof callback === "function" ? callback(res, {
                status: 500,
                content: 'failed to execute query'
              }) : void 0;
            }
            return typeof callback === "function" ? callback(res, {
              status: 200,
              content: results
            }) : void 0;
          });
        });
      };
    })(this);
  }

  return RouteIndex;

})(RikkiTikkiAPI.base_classes.BaseRoute);

module.exports = RouteIndex;
