// Generated by CoffeeScript 1.7.1
var BaseRoute, RouteUpdate,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseRoute = require('./BaseRoute');

RouteUpdate = (function(_super) {
  __extends(RouteUpdate, _super);

  function RouteUpdate(__db, callback) {
    this.__db = __db;
    return (function(_this) {
      return function(req, res) {
        return req.on('data', function(data) {
          var d;
          d = JSON.parse(data);
          return _this.__db.getMongoDB().collection(req.params.collection, function(e, collection) {
            if (d._id != null) {
              delete d._id;
            }
            return collection.update({
              _id: req.params.id
            }, {
              $set: d
            }, function(e, result) {
              if (e != null) {
                return typeof callback === "function" ? callback(res, {
                  status: 500,
                  content: 'failed to execute query'
                }) : void 0;
              }
              return typeof callback === "function" ? callback(res, {
                status: 204,
                content: ''
              }) : void 0;
            });
          });
        });
      };
    })(this);
  }

  return RouteUpdate;

})(BaseRoute);

module.exports = RouteUpdate;
