// Generated by CoffeeScript 1.7.1
var RikkiTikkiAPI, RouteShow,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

RouteShow = (function(_super) {
  __extends(RouteShow, _super);

  function RouteShow(callback) {
    RouteShow.__super__.constructor.call(this);
    return (function(_this) {
      return function(req, res) {
        return req.on('data', function(data) {
          var d;
          _.each(_this.before, function(before, k) {
            return before(req, res, data);
          });
          d = JSON.parse(data);
          return _this.__db.getMongoDB().collection(req.params.collection, function(e, collection) {
            return collection.findOne({
              _id: req.params.id
            }, function(e, result) {
              _.each(_this.after, function(after, k) {
                return after(req, res, result);
              });
              if ((e != null) && (result[0]._id != null)) {
                return typeof callback === "function" ? callback(res, {
                  status: 500,
                  content: 'failed to execute query'
                }) : void 0;
              }
              return typeof callback === "function" ? callback(res, {
                status: 200,
                content: resuilt
              }) : void 0;
            });
          });
        });
      };
    })(this);
  }

  return RouteShow;

})(RikkiTikkiAPI.base_classes.BaseRoute);

module.exports = RouteShow;
