/*
 * LoaderTest.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('../../lib/');

var LoaderTest = new API.Schema(
  API.extend(API.getSchemaTree('LoaderTest'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
LoaderTest.virtuals = {
  
};

/*
 * Static Methods
 */
LoaderTest.statics = {
  
};

/*
 * Custom Schema Validators
 */
LoaderTest.validators = {
  
};

module.exports = API.model('LoaderTest', LoaderTest);