/*
 * CreatedSchema.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var CreatedSchema = new API.Schema(
  API.extend(API.getSchemaTree('CreatedSchema'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
CreatedSchema.virtuals = {
  
};

/*
 * Static Methods
 */
CreatedSchema.statics = {
  
};

/*
 * Custom Schema Validators
 */
CreatedSchema.validators = {
  
};

module.exports[CreatedSchema] = CreatedSchema;