/*
 * SyncTestCollection.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var SyncTestCollection = new API.Schema(
  API.extend(API.getSchemaTree('SyncTestCollection'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
SyncTestCollection.virtuals = {
  
};

/*
 * Static Methods
 */
SyncTestCollection.statics = {
  
};

/*
 * Custom Schema Validators
 */
SyncTestCollection.validators = {
  
};

module.exports[SyncTestCollection] = SyncTestCollection;