/*
 * DeleteMe.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var DeleteMe = new API.Schema(
  API.extend(API.getSchemaTree('DeleteMe'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
DeleteMe.virtuals = {
  
};

/*
 * Static Methods
 */
DeleteMe.statics = {
  
};

/*
 * Custom Schema Validators
 */
DeleteMe.validators = {
  
};

module.exports = API.model('DeleteMe', DeleteMe);