// Generated by CoffeeScript 1.9.3
module.exports = ['Model', 'PersistedModel', 'Email', 'Application', 'AnonymousModel_0', 'AnonymousModel_1', 'AnonymousModel_2', 'AnonymousModel_3', 'AnonymousModel_4', 'AnonymousModel_5', 'AccessToken', 'RoleMapping', 'Role', 'ACL', 'Scope', 'User', 'Change', 'Checkpoint'];
