/*
 * TestSchema.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var _ = require('underscore')._;
var RikkiTikkiAPI = require('../../lib/api');
var TestSchema = new RikkiTikkiAPI.Schema( 
  _.extend(RikkiTikkiAPI.getSchemaTree('TestSchema'),
  {
    value:"foo",
    "new":"param"
  })
);

/*
 * Virtual Getters/Setters
 */
TestSchema.virtuals = {
  
};

/*
 * Static Methods
 */
TestSchema.statics = {
  
};

/*
 * Custom Schema Validators
 */
TestSchema.validators = {
  
};

module.exports = TestSchema;