// Generated by CoffeeScript 1.9.3
var AbstractAdapter, Util, _,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('lodash')._;

Util = require('../utils');

AbstractAdapter = (function(superClass) {
  extend(AbstractAdapter, superClass);

  AbstractAdapter.prototype.required = [];

  function AbstractAdapter(params) {
    this.params = params != null ? params : {};
    if ('AbstractAdapter' === Util.Function.getConstructorName(this)) {
      throw 'AbstractAdapter can not be directly instatiated\nhint: use a subclass instead.';
    }
    _.each(this.required, (function(_this) {
      return function(param) {
        if (!(_this.params.hasOwnProperty(param))) {
          throw Error("required param '" + param + "' was not defined in the adapter params object");
        }
      };
    })(this));
  }

  AbstractAdapter.prototype.requestHandler = function(req, res) {
    throw (Util.Function.getConstructorName(this)) + ".requestHandler(req,res) is not implemented";
  };

  AbstractAdapter.prototype.responseHandler = function(req, res) {
    throw (Util.Function.getConstructorName(this)) + ".responseHandler(req,res) is not implemented";
  };

  AbstractAdapter.prototype.addRoute = function(route, method, handler) {
    throw (Util.Function.getConstructorName(this)) + ".addRoute(route, method, handler) is not implemented";
  };

  return AbstractAdapter;

})(Object);

module.exports = AbstractAdapter;
