// Generated by CoffeeScript 1.9.3
var Hash,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hash = (function(superClass) {
  extend(Hash, superClass);

  function Hash(object, restrict_keys) {
    if (object == null) {
      object = {};
    }
    if (restrict_keys == null) {
      restrict_keys = [];
    }
    Hash.prototype.get = (function(_this) {
      return function(key) {
        return object[key];
      };
    })(this);
    Hash.prototype.set = (function(_this) {
      return function(key, value) {
        var i, k, len, results, v;
        if (typeof key === 'string') {
          if (restrict_keys.length && 0 > restrict_keys.indexOf(key)) {
            return false;
          }
          return object[key] = value;
        } else if (typeof key === 'object') {
          results = [];
          for (v = i = 0, len = key.length; i < len; v = ++i) {
            k = key[v];
            results.push(_this.set(k, v));
          }
          return results;
        }
      };
    })(this);
    Hash.prototype.valueOf = (function(_this) {
      return function() {
        return object;
      };
    })(this);
    Hash.prototype.toJSON = (function(_this) {
      return function() {
        return object;
      };
    })(this);
    Hash.prototype.toString = (function(_this) {
      return function(pretty) {
        if (pretty == null) {
          pretty = false;
        }
        return JSON.stringify(_this.toJSON(), null, pretty ? 2 : void 0);
      };
    })(this);
  }

  return Hash;

})(Object);

module.exports = Hash;
