// Generated by CoffeeScript 1.7.1
var EventEmitter, RikkiTikkiAPI, Singleton,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI;

EventEmitter = require('events').EventEmitter;

Singleton = (function(_super) {
  __extends(Singleton, _super);

  function Singleton() {
    var cName, isDescended, matchSig, _caller, _caller_super;
    cName = RikkiTikkiAPI.Util.Function.getConstructorName(this);
    _caller = arguments.callee.caller.caller;
    _caller_super = arguments.callee.caller;
    while (typeof _caller.__super__ !== 'undefined') {
      _caller_super = _caller;
      _caller = _caller.caller;
    }
    isDescended = (RikkiTikkiAPI.Util.Function.getFunctionName(arguments.callee.caller.__super__.constructor)) === 'Singleton';
    matchSig = ((function(_this) {
      return function(sig) {
        return (sig.replace(/[\n\t]|[\s]{2,}/g, '')) === ("function () {return this.__instance != null ? this.__instance : this.__instance = new " + cName + "();}");
      };
    })(this))(_caller.toString());
    if (!isDescended || !matchSig || typeof _caller_super.getInstance !== 'function') {
      throw "" + cName + " is a Singleton. Try creating/accessing with " + cName + ".getInstance()";
    }
  }

  return Singleton;

})(EventEmitter);

module.exports = Singleton;
