// Generated by CoffeeScript 1.7.1
var APIOptions,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

APIOptions = (function(_super) {
  __extends(APIOptions, _super);

  function APIOptions() {
    this.api_basepath = '/api';
    this.api_version = '1';
    this.api_namespace = '';
    this.db_config_file = 'db.json';
    this.schema_trees_file = 'schema.json';
    this.config_path = 'config';
    this.schema_path = null;
    this.adapter = null;
  }

  return APIOptions;

})(Object);

APIOptions.API_BASEPATH = '/api';

APIOptions.API_VERSION = '1';

APIOptions.API_NAMESPACE = '';

APIOptions.DB_CONFIG_FILE = 'db.json';

APIOptions.SCHEMA_TREES_FILE = 'schema.json';

APIOptions.CONFIG_PATH = 'config';

APIOptions.SCHEMAS = null;

APIOptions.ADAPTER = null;
